import discord
from datetime import datetime
from discord.ext import commands

# Creates a pretty embed containign a link to this bot's source code
class Source(commands.Cog):
    def __init__(self, bot):
        self.bot = bot

    # Add hybrid_command (so it's registered as an app command)
    @commands.hybrid_command()
    async def source(self, ctx):
        # Use the bot's own information to fill in name info
        info = await self.bot.application_info()
        # Generate embed (thanks to https://embed.dan.onl/)
        embed = discord.Embed(title=f"{info.name} on GitHub",
                              url="https://github.com/Savestate2A03/LycanBot",
                              description="A Discord Development bot by Rei Wolf (ie. Savestate) to test out the functionality of Slash commands. \n\nThis bot is in **active development** and contains several extensions that do various things, generally whatever Rei is hyperfixating on at the moment.\n\nDo note that loading and unloading extensions is limited to _Rei only_!",
                              colour=0xff8000,
                              timestamp=datetime.now())
        embed.set_author(name=f"{info.name} Source Code",
                         icon_url="https://i.imgur.com/QPf8ce6.png")
        embed.set_thumbnail(url="https://i.imgur.com/NQUleNR.png")
        embed.set_footer(text=f"Generated by {ctx.author}",
                         icon_url="https://i.imgur.com/e4CYr3e.png")
        await ctx.send(embed=embed)

async def setup(bot):
    await bot.add_cog(Source(bot))